version: '3.8'

services: 
  web:
    build: .
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=
      - DB_USER=
      - DB_PASSWORD=
      - DB_HOST=
      - DB_PORT=
      - SECRET_KEY=
    depends_on:
      - db
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: 
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:  
  db_data: {}
